stages:
  - test

unit debian 10:
  stage: test 
  image: debian:latest
  before_script:
    - apt update
    - apt install -y openjdk-11-jre python3 python3-pip default-libmysqlclient-dev default-mysql-server redis
    - /etc/init.d/mysql start
    - /etc/init.d/redis-server start
  script:
    - bash docker-entrypoint.sh
    - coverage erase
    - coverage run manage.py test lsofadmin
